[package]
name = "mpp"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_decimal = "1.14"
rust_decimal_macros = "1.14"
crossterm="0.20.0"